#!/bin/bash
#SBATCH --partition=multi
#SBATCH --time=4-00:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
. /etc/profile
srun echo $(seq 1 20000) | xargs -P 32 -n 1 bash attack.sh ER 16000 5.00 DegU